src/Entity/Piece.php
<?php

namespace App\Entity;

use IntlDateFormatter;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use App\Repository\PieceRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: PieceRepository::class)]
class Piece
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $about = null;

    #[ORM\Column(length: 255)]
    private ?string $maker = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $releaseDate = null;

    /**
     * @var Collection<int, Image>
     */
    #[ORM\OneToMany(targetEntity: Image::class, mappedBy: 'piece', orphanRemoval: true, cascade: ['persist'])]
    private Collection $images;

    /**
     * @var Collection<int, Video>
     */
    #[ORM\OneToMany(targetEntity: Video::class, mappedBy: 'piece', orphanRemoval: true, cascade: ['persist'])]
    private Collection $videos;

    #[ORM\ManyToOne(inversedBy: 'pieces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    /**
     * @var Collection<int, Critic>
     */
    #[ORM\OneToMany(targetEntity: Critic::class, mappedBy: 'piece', orphanRemoval: true)]
    private Collection $critics;

    /**
     * @var Collection<int, Opinion>
     */
    #[ORM\OneToMany(targetEntity: Opinion::class, mappedBy: 'piece', orphanRemoval: true)]
    private Collection $opinions;

    #[ORM\Column(nullable: true)]
    private ?bool $isUpcoming = null;

    #[ORM\Column(length: 255)]
    private ?string $poster = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'pieces')]
    private Collection $users;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->critics = new ArrayCollection();
        $this->opinions = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(string $about): static
    {
        $this->about = $about;

        return $this;
    }

    public function getMaker(): ?string
    {
        return $this->maker;
    }

    public function setMaker(string $maker): static
    {
        $this->maker = $maker;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->releaseDate;
    }

    // > English date formatter fonction
    public function getReleaseDateENG(): ?string 
    {        
        return $this->releaseDate->format('M. jS, Y');
    }

    public function setReleaseDate(\DateTimeInterface $releaseDate): static
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    // TO STRING -> Piece title
    public function __toString()
    {
        return $this->title;
    }

    
    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setPiece($this);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getPiece() === $this) {
                $image->setPiece(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): static
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setPiece($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): static
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getPiece() === $this) {
                $video->setPiece(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Critic>
     */
    public function getCritics(): Collection
    {
        return $this->critics;
    }

    public function addCritic(Critic $critic): static
    {
        if (!$this->critics->contains($critic)) {
            $this->critics->add($critic);
            $critic->setPiece($this);
        }

        return $this;
    }

    public function removeCritic(Critic $critic): static
    {
        if ($this->critics->removeElement($critic)) {
            // set the owning side to null (unless already changed)
            if ($critic->getPiece() === $this) {
                $critic->setPiece(null);
            }
        }

        return $this;
    }

    public function getCriticTotalScore(): ?float{
        
        $totalScore = 0;

        foreach ($this->critics as $critic) {
            $totalScore += $critic->getCriticScore();
            
        }
        return round(($totalScore / count($this->critics)*2), 1);
    }

    /**
     * @return Collection<int, Opinion>
     */
    public function getOpinions(): Collection
    {
        return $this->opinions;
    }

    public function addOpinion(Opinion $opinion): static
    {
        if (!$this->opinions->contains($opinion)) {
            $this->opinions->add($opinion);
            $opinion->setPiece($this);
        }

        return $this;
    }

    public function removeOpinion(Opinion $opinion): static
    {
        if ($this->opinions->removeElement($opinion)) {
            // set the owning side to null (unless already changed)
            if ($opinion->getPiece() === $this) {
                $opinion->setPiece(null);
            }
        }

        return $this;
    }

    public function getUserTotalScore(): ?float{
        
        $totalScore = 0;

        foreach ($this->opinions as $opinion) {
            $totalScore += $opinion->getUserScore();
        }
        return round(($totalScore / count($this->opinions)*2), 1);
    }

    public function isUpcoming(): ?bool
    {
        return $this->isUpcoming;
    }

    public function setIsUpcoming(?bool $isUpcoming): static
    {
        $this->isUpcoming = $isUpcoming;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addPiece($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removePiece($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/PieceController.php
<?php

namespace App\Controller;

use App\Entity\Piece;
use App\Entity\Category;
use App\Form\PieceFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class PieceController extends AbstractController
{
    // -> Add or edit a Piece
    #[Route('/piece/new', name: 'new_piece')]
    #[Route('/piece/{id}/edit', name: 'edit_piece')]
    public function new_edit(Piece $piece = null, 
    Request $request, 
    EntityManagerInterface $entityManager,
    SluggerInterface $slugger,
    CsrfTokenManagerInterface $csrf,
    #[Autowire('%kernel.project_dir%/public/uploads/images')] string $imagesDirectory
    ): Response
    {
        // > If Piece does not exist, create Piece
        if (!$piece) {
            $piece = new Piece();
        }
        $form = $this->createForm(PieceFormType::class, $piece);
        
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            // > Fetching datas from the submitted form
            $piece = $form->getData();
            $posterFile = $form->get('poster')->getData();
            
            // foreach ($images as $image) {
                
            //     $imagePath = $image->getLink(); 
            //     $imageTitle = $image->getTitle();
                
            //     $imageFile = new UploadedFile($imagePath, $imageTitle);

            // > If a new poster is submitted
            if ($posterFile) {

                // > Delete Piece's previous poster
                $posterName = $piece->getPoster();

                if ($posterName) {
                    $posterPath = $this->getParameter('kernel.project_dir') . '/public/uploads/images/'.$posterName;
            
                    if (file_exists($posterPath)) {
                        unlink($posterPath);
                    }
                }

                $originalFileName = pathinfo($posterFile->getClientOriginalName(), PATHINFO_FILENAME);
                $safeFileName = $slugger->slug($originalFileName);
                $newFileName = $safeFileName.'-'.uniqid().'.'.$posterFile->guessExtension();
                
                // > Moving uploaded poster to directory
                try {
                    $posterFile->move($imagesDirectory, $newFileName);
                    // $image->setLink($newFileName);
                } catch (FileException $e) {
                    ('An error occured while uploading the file : '.$e->getMessage()); die;
                }
            } 
            // > Else : photo stays the same
            else {
                $newFileName = $piece->getPoster();
            }

            // > Poster is set with file name in the entity
            $piece->setPoster($newFileName);

            // > 2 steps save in DataBase
            $entityManager->persist($piece);
            $entityManager->flush();

            $this->addFlash('piAddEditSuccess', ' "'.$piece.'" added/edited !');
            return $this->redirectToRoute('infos_piece', ['slug' => $piece->getSlug()]);
        }
        
        // > Return infos to view
        return $this->render('piece/new.html.twig', [
            'formAddPiece' => $form,
            'edit' => $piece->getId()
        ]);
    }

    // -> Delete a Piece
    #[Route('/piece/{id}/delete', name: 'delete_piece')]
    public function delete(Piece $piece, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($piece);
        $entityManager->flush();

        $this->addFlash('piDeleteSuccess', ' "'.$piece.'" deleted !');
        return $this->redirectToRoute('app_home');
    }

    // > Display pieces by Category
    #[Route('/category/{slug:category}', name: 'show_category')]
    public function show(Category $category = null): Response
    {
        if (!$category) {
            $this->addFlash('caSearchFail', 'The category you\'re looking for does not exist !');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('piece/index.html.twig', [
            'category' => $category,
        ]);
    }

    // > Display piece details
    #[Route('/piece/{slug:piece}/infos', name: 'infos_piece')]
    public function infosPiece(Piece $piece = null): Response
    {
        if (!$piece) {
            $this->addFlash('piSearchFail', 'The piece you\'re looking for does not exist !');
            return $this->redirectToRoute('app_home');
        }

        return $this->render('piece/infos.html.twig', [
            'piece' => $piece
        ]);
    }
}

templates/piece/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CritX > {{category}}{% endblock %}

{% block body %}

<div id="pieceListContainer">
    <h1>All {{category}}<sup>({{category.pieces|length}})</sup></h1>
    {% if app.user and "ROLE_ADMIN" in app.user.roles %}
        <a href="{{ path('new_piece')}}">Add a Piece</a><br>
        <a href="{{ path('new_critic')}}">Add a Critic</a>
    {% endif %}
    <hr>

    <div id="pieceList">
        {% for piece in category.pieces|sort((a, b) => b.releaseDate <=> a.releaseDate) %}

            <section id="onePieceList">
                <h2><a href="{{ path('show_critics', {'slug': piece.slug})}}">{{piece}}</a></h2>

                {% if piece.category == "Music" %}
                <a href="{{ path('show_critics', {'slug': piece.slug})}}">
                    <img id="musicPieceList" src="/uploads/images/{{piece.poster}}" alt="{{piece}}-visual">
                </a>

                {% else %}
                <a href="{{ path('show_critics', {'slug': piece.slug})}}">
                    <img src="/uploads/images/{{piece.poster}}" alt="{{piece}}-visual">
                </a>

                {% endif %}

                <div id="onePieceListScoreContainer">
                    {% if piece.critics|length > 0 %}
                        <div id="onePieceListScore">
                            <strong>Critic score</strong>

                            {% if piece.criticTotalScore >= 6.6 %}
                                <div id="onePieceListScoreToken" class="goodScore">
                            {% elseif piece.criticTotalScore <= 6.6 and piece.criticTotalScore >= 3.3 %}
                                <div id="onePieceListScoreToken" class="averageScore">
                            {% else %}
                                <div id="onePieceListScoreToken" class="badScore">
                            {% endif %}
                            
                                {{ piece.criticTotalScore }}
                                <hr>
                                10
                            </div>
                        </div>
                    {% endif %}

                    {% if piece.opinions|length > 0 %}
                        <div id="onePieceListScore">
                            <strong>User score</strong>

                            {% if piece.userTotalScore >= 6.6 %}
                                <div id="onePieceListScoreToken" class="goodScore">
                            {% elseif piece.userTotalScore <= 6.6 and piece.userTotalScore >= 3.3 %}
                                <div id="onePieceListScoreToken" class="averageScore">
                            {% else %}
                                <div id="onePieceListScoreToken" class="badScore">
                            {% endif %}

                                {{ piece.userTotalScore }}
                                <hr>
                                10
                            </div>
                        </div>
                    {% else %}
                        <div id="onePieceListScore">
                            <strong>User score</strong>
                            <div id="onePieceListScoreToken" class="noScore">
                                -
                                <hr>
                                10
                            </div>
                        </div>
                    {% endif %}
                </div>
                <div id="onePieceListText">
                    <strong>Maker : </strong>{{piece.maker}}<br>
                    
                    {% if piece.isUpcoming %}
                        <strong>Release date : </strong>{{piece.releaseDateENG|date("Y") }} (Upcoming)
                    {% else %}
                        <strong>Release date : </strong>{{piece.releaseDateENG}}
                    {% endif %}
                </div>
            </section>
        {% endfor %}
    </div>
</div>
            
{% endblock %}
            
    

templates/piece/infos.html.twig
{% extends 'base.html.twig' %}

{% block title %}CritX > {{piece.category}} > Infos > {{piece}}{% endblock %}

{% block body %}

<div id="pieceContainer">
    <div id="pieceSubContainer">
        <div id="pieceInfos">
            <div id="pieceInfosImage">
                {% if piece.category == "Music" %}
                    <img id="musicPieceInfos" src="/uploads/images/{{piece.poster}}" alt="{{piece}}-visual">
                {% else %}
                    <img src="/uploads/images/{{piece.poster}}" alt="{{piece}}-visual">
                {% endif %}
            </div>

            <div id="pieceInfosText">
                <i>#{{piece.category}} > Infos</i>
                <h2>Infos on →</h2>
                <h1>{{piece}}</h1>

                <div id="pieceInfosTextPara">
                    <strong>Maker : </strong>{{piece.maker}}<br>

                    {% if piece.isUpcoming %}
                        <strong>Release date : </strong>{{piece.releaseDateENG|date("Y") }} (Upcoming)<br>
                    {% else %}
                        <strong>Release date : </strong>{{piece.releaseDateENG}}
                    {% endif %}
                    
                    <p><strong>About : </strong>{{piece.about}}</p>

                    {# > Edit and suppression (modal) #}
                    {% if app.user and "ROLE_ADMIN" in app.user.roles %}
                        <a href="{{ path('edit_piece', {'id': piece.id})}}"><button style="width: 50px; padding: 2.5px;">Edit</button></a>
                        {# <a href="{{ path('delete_influencer', {'id': influencer.id})}}">Delete</a></h2><br> #}
                        <button class="deleteConfirm" style="width: 50px; padding: 2.5px;">Delete</button><br>
                        <dialog class="openModal">
                            <h3>Are you sure you want to delete "{{piece}}" ?</h3>
                            <a href="{{ path('delete_piece', {'id': piece.id})}}"><button>Yes</button></a>
                            <button class="closeModal">No</button>
                        </dialog>
                    {% endif %}
                </div>
            </div>
        </div>

        <div id="pieceScores">

            {# > User score and opinion ID fetch #}
            {% set userScore = null %}
            {% set opinionId = null %}
            {% for opinion in piece.opinions %}
                {% if app.user and app.user.id == opinion.user.id %}
                    {% set userScore = opinion.userScore %}
                    {% set opinionId = opinion.id %}
                {% endif %}
            {% endfor %}

            {# > Switch > User score vote or User score display #}
            {% if userScore %}

                {# > Star score system #}
                <div class="user-score-display-container">
                    <h2>Your Score</h2>
                    <div class="user-score-display">
                        {% set note = userScore %}
                        {# {% set fullStars = note|round(0, 'floor') %} #}
                        {% set fullStars = note %}
                        {# {% set partialStar = (note - fullStars)|round(0, 'ceil') %} #}
                        {% set emptyStars = 5 - fullStars %}
                        {# {% set emptyStars = 5 - fullStars - (partialStar ? 1 : 0) %} #}
                    
                        {% for i in range(1, fullStars) %}
                            <i class="fa-solid fa-star fullstars"></i>
                        {% endfor %}

                        {# {% if partialStar %}
                            <i class="fa-solid fa-star-half-stroke halfstars"></i>
                        {% endif %} #}

                        {% if emptyStars %}
                            {% for i in range(1, emptyStars) %}
                                <i class="fa-solid fa-star emptystars"></i>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <small>Your score has been set !</small>
                    <button class="deleteConfirm user-score-reset">Reset vote</button><br>
                        <dialog class="openModal">
                            <h3>Are you sure you want to reset your score on "{{piece}}" ?</h3>
                            <a href="{{ path('score_reset', {'piece': piece.id, 'opinion': opinionId})}}"><button>Yes</button></a>
                            <button class="closeModal">No</button>
                        </dialog>
                </div>

            {% else %}
                
                <form class="user-score-form" method="post" action="{{ path('score_piece', {'id': piece.id})}}">
                    <h2>Your Score</h2>
                    <fieldset class="user-score">
                        <legend class="accessLabel">User score vote</legend>
                        <input type="radio" name="rating" id="rating5" value="5" required>
                        <label class="fa-solid fa-star emptystars" for="rating5"></label>
                        <input type="radio" name="rating" id="rating4" value="4" required>
                        <label class="fa-solid fa-star emptystars" for="rating4"></label>
                        <input type="radio" name="rating" id="rating3" value="3" required>
                        <label class="fa-solid fa-star emptystars" for="rating3"></label>
                        <input type="radio" name="rating" id="rating2" value="2" required>
                        <label class="fa-solid fa-star emptystars" for="rating2"></label>
                        <input type="radio" name="rating" id="rating1" value="1" required>
                        <label class="fa-solid fa-star emptystars" for="rating1"></label>
                    </fieldset><br>
                    <small>Please set a score between 1 & 5</small>
                    <input type="hidden" name="_token" value="{{ csrf_token('rating_add') }}">
                    <input type="submit" name="submit" class="user-score-submit" value="Vote !">
                </form>

            {% endif %}

            <div id="infosScoreContainer">
                {% if piece.critics|length > 0 %}
                    <div id="onePieceScore">
                        <strong>Critic score</strong>

                        {% if piece.criticTotalScore >= 6.6 %}
                            <div id="onePieceScoreToken" class="goodScore">
                        {% elseif piece.criticTotalScore <= 6.6 and piece.criticTotalScore >= 3.3 %}
                            <div id="onePieceScoreToken" class="averageScore">
                        {% else %}
                            <div id="onePieceScoreToken" class="badScore">
                        {% endif %}

                            {{piece.criticTotalScore}}
                            <hr>
                            10
                        </div>
                    </div>
                {% endif %}

                {% if piece.opinions|length > 0 %}
                    <div id="onePieceScore">
                        <strong>User score</strong>

                        {% if piece.userTotalScore >= 6.6 %}
                            <div id="onePieceScoreToken" class="goodScore">
                        {% elseif piece.userTotalScore <= 6.6 and piece.userTotalScore >= 3.3 %}
                            <div id="onePieceScoreToken" class="averageScore">
                        {% else %}
                            <div id="onePieceScoreToken" class="badScore">
                        {% endif %}
                
                            {{ piece.userTotalScore }}
                            <hr>
                            10
                        </div>
                    </div>
            {% else %}
                <div id="onePieceScore">
                <strong>User score</strong>
                    <div id="onePieceScoreToken" class="noScore">
                        -
                        <hr>
                        10
                    </div>
                </div>
            {% endif %}

            {# {% for image in piece.images %}
                {{image}}
            {% endfor %} #}

            </div>

            <h2>Go to critics →</h2>
            <a href="{{ path('show_critics', {'slug': piece.slug})}}">{{piece}}</a>
        </div>
    </div>

    {% if piece.videos|length > 0 %}

        <h3>Trailer</h3>
        <hr>

        {% for video in piece.videos %}
            <div id="pieceVideo">
                {# <iframe width="560" height="315" src="{{video.link}}" 
                title="YouTube video player" 
                frameborder="0" 
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
                referrerpolicy="strict-origin-when-cross-origin" 
                allowfullscreen></iframe> #}
                <div class="youtube_player" 
                videoID="{{video.link}}" 
                theme="theme (dark | light)" 
                rel="rel (1 | 0)" 
                controls="controls (1 | 0)" 
                showinfo="showinfo (1 | 0)" 
                autoplay="autoplay (0 | 1)" 
                mute="mute (0 | 1)" 
                loop="loop (0 | 1)" 
                loading="loading (0 | 1)" 
                data-start="start" 
                data-end="end"></div>
            </div>
        {% endfor %}

    {% endif %}

    <a class="nextLink" href="{{path('show_category', {'slug': piece.category.slug})}}"><i>> View all {{piece.category}}</i></a>
</div>
   
{% endblock %}
        

            
      
            
            
            
        



                
            




    
    
            

            

            
            

templates/piece/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if edit %}
    Edit Piece
    {% else %}
    Add Piece
    {% endif %}
{% endblock %}

{% block body %}
    {% if edit %}
    <h1>Edit a Piece</h1><br>
    {% else %}
    <h1>Add a Piece</h1><br>
    {% endif %}

    {{ form_start(formAddPiece) }}
    
        {{ form_row(formAddPiece.title) }}<br>
        {{ form_row(formAddPiece.about) }}<br>
        {{ form_row(formAddPiece.maker) }}
        {{ form_row(formAddPiece.releaseDate) }}
        {{ form_row(formAddPiece.isUpcoming) }}
        {{ form_row(formAddPiece.poster) }}
        {{ form_row(formAddPiece.category) }}<br>

        {# > "Add images" forms prototypes #}
        <button type="button" class="addFormImagesLink" data-collection-holder-class="addFormImages">Add images</button><br><br>
        <ul class="addFormImages"
        data-index="{{ formAddPiece.images|length > 0 ? formAddPiece.images|last.vars.name + 1 : 0}}"
        data-prototype="{{ form_widget(formAddPiece.images.vars.prototype)|e('html_attr')}}">
        </ul>

        {# > "Add videos" forms prototypes #}
        <button type="button" class="addFormVideosLink" data-collection-holder-class="addFormVideos">Add videos</button><br><br>
        <ul class="addFormVideos"
        data-index="{{ formAddPiece.videos|length > 0 ? formAddPiece.videos|last.vars.name + 1 : 0}}"
        data-prototype="{{ form_widget(formAddPiece.videos.vars.prototype)|e('html_attr')}}">
        </ul>

        {{ form_row(formAddPiece.validate) }}<br><br>

    {{ form_end(formAddPiece) }}

{% endblock %}

templates/piece/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Critix > {{piece.category}} > Infos > {{piece}}{% endblock %}

{% block body %}

<div>
    <i>#{{piece.category}} > Infos</i>
    <h2>Infos on →</h2>
    <h1>{{piece}}</h1>

    {# > Edit and suppression (modal) #}
    <a href="{{ path('edit_piece', {'id': piece.id})}}"><button>Edit</button></a>
    {# <a href="{{ path('delete_influencer', {'id': influencer.id})}}">Delete</a></h2><br> #}
    <button class="deleteConfirm">Delete</button><br>
        <dialog class="openModal">
            <h3>Are you sure you want to delete "{{piece}}" ?</h3>
            <a href="{{ path('delete_piece', {'id': piece.id})}}"><button>Yes</button></a>
            <button class="closeModal">No</button>
        </dialog>

    {% if piece.isUpcoming %}
        <p><u>Release date</u> : {{piece.releaseDateENG|date("Y") }} (Upcoming)</p>
    {% else %}
        <p><u>Release date</u> : {{piece.releaseDateENG}}</p>
    {% endif %}
    
    <p><u>Maker</u> : {{piece.maker}}</p>
    <p><u>About</u> : {{piece.about}}</p>
    {# {% for image in piece.images %}
        {{image}}
    {% endfor %} #}
    <h2>Go to critics <br>
    → <a href="{{ path('show_critics', {'id': piece.id})}}">{{piece}}</a></h2>
    <a href="{{path('show_category', {'id': piece.category.id})}}"><i>> View all {{piece.category}} critics</i></a>
</div>
   
{% endblock %}