src/Entity/Critic.php
<?php

namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\CriticRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CriticRepository::class)]
class Critic
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $media = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $summary = null;

    #[ORM\Column(options:["default" => 0])]
    private ?float $criticScore = null;

    #[ORM\Column(options:["default" => 0])]
    private ?int $lengthMin = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, options:["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $datePost = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Assert\LessThanOrEqual(value: new \DateTime('today'), message: "Date cannot be set in the future")]
    private ?\DateTimeInterface $originDatePost = null;

    #[ORM\ManyToOne(inversedBy: 'critics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Piece $piece = null;

    #[ORM\ManyToOne(inversedBy: 'critics')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Influencer $influencer = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'critics')]
    private Collection $users;

    /**
     * @var Collection<int, Agreement>
     */
    #[ORM\OneToMany(targetEntity: Agreement::class, mappedBy: 'critic', orphanRemoval: true)]
    private Collection $agreements;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'critic', orphanRemoval: true)]
    private Collection $comments;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->agreements = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->datePost = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMedia(): ?string
    {
        return $this->media;
    }

    public function setMedia(string $media): static
    {
        $this->media = $media;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(string $summary): static
    {
        $this->summary = $summary;

        return $this;
    }

    public function getCriticScore(): ?float
    {
        return $this->criticScore;
    }

    public function setCriticScore(float $criticScore): static
    {
        $this->criticScore = $criticScore;

        return $this;
    }

    public function getLengthMin(): ?int
    {
        return $this->lengthMin;
    }

    public function setLengthMin(int $lengthMin): static
    {
        $this->lengthMin = $lengthMin;

        return $this;
    }

    public function getDatePost(): ?\DateTimeInterface
    {
        return $this->datePost;
    }

    // > English date formatter fonction
    public function getDatePostENG(): ?string 
    {        
        return $this->datePost->format('M. jS, Y');
    }

    public function setDatePost(\DateTimeInterface $datePost): static
    {
        $this->datePost = $datePost;

        return $this;
    }

    public function getOriginDatePost(): ?\DateTimeInterface
    {
        return $this->originDatePost;
    }

    // > English date formatter fonction
    public function getOriginDatePostENG(): ?string 
    {        
        return $this->originDatePost->format('M. jS, Y');
    }

    public function setOriginDatePost(\DateTimeInterface $originDatePost): static
    {
        $this->originDatePost = $originDatePost;

        return $this;
    }

    // TO STRING -> Critic score on 5
    public function __toString()
    {
        return $this->criticScore;
    }

    public function getPiece(): ?Piece
    {
        return $this->piece;
    }

    public function setPiece(?Piece $piece): static
    {
        $this->piece = $piece;

        return $this;
    }

    public function getInfluencer(): ?Influencer
    {
        return $this->influencer;
    }

    public function setInfluencer(?Influencer $influencer): static
    {
        $this->influencer = $influencer;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        $this->users->removeElement($user);

        return $this;
    }

    /**
     * @return Collection<int, Agreement>
     */
    public function getAgreements(): Collection
    {
        return $this->agreements;
    }

    public function addAgreement(Agreement $agreement): static
    {
        if (!$this->agreements->contains($agreement)) {
            $this->agreements->add($agreement);
            $agreement->setCritic($this);
        }

        return $this;
    }

    public function removeAgreement(Agreement $agreement): static
    {
        if ($this->agreements->removeElement($agreement)) {
            // set the owning side to null (unless already changed)
            if ($agreement->getCritic() === $this) {
                $agreement->setCritic(null);
            }
        }

        return $this;
    }

    public function getTotalAgreements(): ?float{
        
        $totalAgreements = 0;

        foreach ($this->agreements as $agreement) {
            $totalAgreements += $agreement->isOk();
        }
        return round(($totalAgreements / count($this->agreements))*100, 1);
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setCritic($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getCritic() === $this) {
                $comment->setCritic(null);
            }
        }

        return $this;
    }
}

src/Entity/Piece.php
<?php

namespace App\Entity;

use IntlDateFormatter;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation\Slug;
use App\Repository\PieceRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

#[ORM\Entity(repositoryClass: PieceRepository::class)]
class Piece
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $about = null;

    #[ORM\Column(length: 255)]
    private ?string $maker = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $releaseDate = null;

    /**
     * @var Collection<int, Image>
     */
    #[ORM\OneToMany(targetEntity: Image::class, mappedBy: 'piece', orphanRemoval: true, cascade: ['persist'])]
    private Collection $images;

    /**
     * @var Collection<int, Video>
     */
    #[ORM\OneToMany(targetEntity: Video::class, mappedBy: 'piece', orphanRemoval: true, cascade: ['persist'])]
    private Collection $videos;

    #[ORM\ManyToOne(inversedBy: 'pieces')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    /**
     * @var Collection<int, Critic>
     */
    #[ORM\OneToMany(targetEntity: Critic::class, mappedBy: 'piece', orphanRemoval: true)]
    private Collection $critics;

    /**
     * @var Collection<int, Opinion>
     */
    #[ORM\OneToMany(targetEntity: Opinion::class, mappedBy: 'piece', orphanRemoval: true)]
    private Collection $opinions;

    #[ORM\Column(nullable: true)]
    private ?bool $isUpcoming = null;

    #[ORM\Column(length: 255)]
    private ?string $poster = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'pieces')]
    private Collection $users;

    #[ORM\Column(length: 100, unique: true)]
    #[Slug(fields: ['title'])]
    private ?string $slug = null;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
        $this->critics = new ArrayCollection();
        $this->opinions = new ArrayCollection();
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(string $about): static
    {
        $this->about = $about;

        return $this;
    }

    public function getMaker(): ?string
    {
        return $this->maker;
    }

    public function setMaker(string $maker): static
    {
        $this->maker = $maker;

        return $this;
    }

    public function getReleaseDate(): ?\DateTimeInterface
    {
        return $this->releaseDate;
    }

    // > English date formatter fonction
    public function getReleaseDateENG(): ?string 
    {        
        return $this->releaseDate->format('M. jS, Y');
    }

    public function setReleaseDate(\DateTimeInterface $releaseDate): static
    {
        $this->releaseDate = $releaseDate;

        return $this;
    }

    // TO STRING -> Piece title
    public function __toString()
    {
        return $this->title;
    }

    
    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): static
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setPiece($this);
        }

        return $this;
    }

    public function removeImage(Image $image): static
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getPiece() === $this) {
                $image->setPiece(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): static
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setPiece($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): static
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getPiece() === $this) {
                $video->setPiece(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Critic>
     */
    public function getCritics(): Collection
    {
        return $this->critics;
    }

    public function addCritic(Critic $critic): static
    {
        if (!$this->critics->contains($critic)) {
            $this->critics->add($critic);
            $critic->setPiece($this);
        }

        return $this;
    }

    public function removeCritic(Critic $critic): static
    {
        if ($this->critics->removeElement($critic)) {
            // set the owning side to null (unless already changed)
            if ($critic->getPiece() === $this) {
                $critic->setPiece(null);
            }
        }

        return $this;
    }

    public function getCriticTotalScore(): ?float{
        
        $totalScore = 0;

        foreach ($this->critics as $critic) {
            $totalScore += $critic->getCriticScore();
            
        }
        return round(($totalScore / count($this->critics)*2), 1);
    }

    /**
     * @return Collection<int, Opinion>
     */
    public function getOpinions(): Collection
    {
        return $this->opinions;
    }

    public function addOpinion(Opinion $opinion): static
    {
        if (!$this->opinions->contains($opinion)) {
            $this->opinions->add($opinion);
            $opinion->setPiece($this);
        }

        return $this;
    }

    public function removeOpinion(Opinion $opinion): static
    {
        if ($this->opinions->removeElement($opinion)) {
            // set the owning side to null (unless already changed)
            if ($opinion->getPiece() === $this) {
                $opinion->setPiece(null);
            }
        }

        return $this;
    }

    public function getUserTotalScore(): ?float{
        
        $totalScore = 0;

        foreach ($this->opinions as $opinion) {
            $totalScore += $opinion->getUserScore();
        }
        return round(($totalScore / count($this->opinions)*2), 1);
    }

    public function isUpcoming(): ?bool
    {
        return $this->isUpcoming;
    }

    public function setIsUpcoming(?bool $isUpcoming): static
    {
        $this->isUpcoming = $isUpcoming;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->poster;
    }

    public function setPoster(string $poster): static
    {
        $this->poster = $poster;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addPiece($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            $user->removePiece($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PieceRepository;
use App\Repository\CommentRepository;
use App\Repository\CategoryRepository;
use App\Repository\InfluencerRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

final class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(PieceRepository $pieceRepository, InfluencerRepository $influencerRepository, CommentRepository $commentRepository)
    {

        $pieces = $pieceRepository->findBy([], ["releaseDate" => "DESC"]);
        $influencers = $influencerRepository->findBy([], ["nickName" => "DESC"]);
        $vipComments = $commentRepository->findBy(['isVIP' => 1], ["datePost" => "DESC"]);

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'pieces' => $pieces,
            'influencers' => $influencers,
            'vipComments' => $vipComments
        ]);
    }

    #[Route('/about', name: 'app_about')]
    public function indexAbout()
    {

        return $this->render('home/about.html.twig', [
        ]);
    }

    #[Route('/legal', name: 'app_legal')]
    public function indexLegal()
    {

        return $this->render('home/legal.html.twig', [
        ]);
    }

    #[Route('/privacy', name: 'app_privacy')]
    public function indexPrivacy()
    {

        return $this->render('home/privacy.html.twig', [
        ]);
    }
}

templates/home/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}CritX > About{% endblock %}

{% block body %}

<div class="footInfosContainer">
    <div class="footInfos" id="aboutInfos">
        <h1>About CritX</h1>
        <h2>(FAQs)</h2>

        <section>
            <h3>- What’s a "Critic score ?"</h3>
            
            <p>The "Critic Score" is a single score that represents the critical consensus for Games, Movies, TV Shows, Music albums, Books and Comics/Mangas.
            The CritX's editorial team curate a diverse group of highly respected YouTubers/content creators and we assign scores on five stars to their reviews.
            The weighted average of those scores results in a single number on ten : the "Critic Score".</p>
        </section>

        <section>
            <h3>- What’s a "User score ?"</h3>

            <p>The "User Score" is based on the same consensus system than the "Critic Score".
            Every registered and logged in User (yes, we mean "you") has the possiblity to set a score from one to five stars to a piece, 
            directly via the "infos page" of the related piece.
            The weighted average of all CritX’s users scores on one piece results in a single number on ten : the "User Score".</p>
        </section>

        <section>
            <h3>- What’s a "Comment of the Week ?"</h3>

            <p>At CritX, we think that well written comments can be similar to a proper critic and maybe deserve a subsequent highlight.
            That’s why every week, the CritX’s editorial team can select a relevant comment related to a content creator’s critic, and highlight it, 
            aside from other users’ comments.
            However, some informations about this feature needs to be submitted for your consideration :</p>

            <ul>
                <li>By commenting a content creator’s critic, you tacilty agree to the possibility that your comment may be selected and highlight, for one week, 
                by the CritX’s editorial team.</li>
                <li>A User Score MUST have been set on the related piece by the potentially selected user, so that his/her personnal score can be associated 
                with the comment/critic and displayed in the "Comment of the Week" section.</li>
                <li>In order to be selected, a comment should be part of a more global context of reviewing a piece, 
                rather than a simple reaction to the critic of a content creator.</li>
            </ul>
        </section>
    </div>
<div>

{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}CritX : Video Reviews of Games, Movies, Music, Books...by content creators{% endblock %}

{% block banner %}
    <div id="homeBanner">
        <h1><em>For every culture, there's a Youtuber</em></h1>
        <a href="{{ path('random_critics')}}">Discover</a>
    </div>
{% endblock %}

{% block body %}

<div id="homeContainer">
    <section id="pieceListContainerHome">
        <h2>Latest releases</h2>
        <hr>

        <div id="pieceListHome">
            {% for piece in pieces|slice(0, 3) %}
                <div id="onePieceListHome">
                    {% if piece.category == "Music" %}
                    <a href="{{ path('infos_piece', {'slug': piece.slug})}}">
                        <img id="musicPieceListHome" src="/uploads/images/{{piece.poster}}" alt="{{piece}}-visual">
                    </a>
                    {% else %}
                    <a href="{{ path('infos_piece', {'slug': piece.slug})}}">
                        <img src="/uploads/images/{{piece.poster}}" alt="{{piece}}-visual">
                    </a>
                    {% endif %}

                    <h3><a href="{{ path('infos_piece', {'slug': piece.slug})}}">{{piece}}</a></h3>
                    <i>#{{piece.category}}</i>

                    <div id="onePieceListScoreContainerHome">
                        {% if piece.critics|length > 0 %}
                            <div id="onePieceListScoreHome">
                                <strong>Critic score</strong>

                                {% if piece.criticTotalScore >= 6.6 %}
                                    <div id="onePieceListScoreTokenHome" class="goodScore">
                                {% elseif piece.criticTotalScore <= 6.6 and piece.criticTotalScore >= 3.3 %}
                                    <div id="onePieceListScoreTokenHome" class="averageScore">
                                {% else %}
                                    <div id="onePieceListScoreTokenHome" class="badScore">
                                {% endif %}
                                
                                    {{ piece.criticTotalScore }}
                                    <hr>
                                    10
                                </div>
                            </div>
                        {% endif %}

                        {% if piece.opinions|length > 0 %}
                            <div id="onePieceListScoreHome">
                                <strong>User score</strong>

                                {% if piece.userTotalScore >= 6.6 %}
                                    <div id="onePieceListScoreTokenHome" class="goodScore">
                                {% elseif piece.userTotalScore <= 6.6 and piece.userTotalScore >= 3.3 %}
                                    <div id="onePieceListScoreTokenHome" class="averageScore">
                                {% else %}
                                    <div id="onePieceListScoreTokenHome" class="badScore">
                                {% endif %}

                                    {{ piece.userTotalScore }}
                                    <hr>
                                    10
                                </div>
                            </div>
                        {% else %}
                            <div id="onePieceListScoreHome">
                                <strong>User score</strong>
                                <div id="onePieceListScoreTokenHome" class="noScore">
                                    -
                                    <hr>
                                    10
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    <hr>
    </section>

    <section>
        <h1><em>Watch, comment and react to what they think</em></h1>
    </section>

    <section id="influListContainerHome">

        <h2>They are on CritX</h2>
        <hr>
    
        <div id="influencerListHome">
            {% for influencer in influencers
                |filter(i => i.photo is not empty)
                |slice(0, 8) %}

                <div id="oneInfluencerListHome">
                
                    <a href="{{ path('show_influencer', {'slug': influencer.slug})}}">
                        <img src="/uploads/photos/influPhotos/{{influencer.photo}}" alt="{{influencer}}-picture">
                    </a>

                    <h3><a href="{{ path('show_influencer', {'slug': influencer.slug})}}">{{influencer}}</a></h3>

                    {# > If Influencer's real name is known #}
                    {% if influencer.realName and influencer != influencer.realName %}
                        <h4>({{influencer.realname}})</h4>
                    {% endif %}

                </div>

                {# {% endif %} #}
            {% endfor %}
        </div>
    </section>

    <section id="vipCommentListContainerHome">

        <h2>Comments of the week</h2>
        <hr>

        <div id="vipCommentListHome">
            {% for vipComment in vipComments|slice(0, 2) %}

            <div id="vipCommentListSubContainerHome">
                <article class="commentDisplay">
                        
                    <div id="vipCommentTitleHome">
                        <h4>Comment of the Week</h4>
                        <i class="fa-solid fa-medal vipIcon"></i>
                    </div>
                
                    <div id="vipCommentContentHome">
                        {% if vipComment.user.profilePicture %}
                            <a class="ppLink" href="{{ path('show_user', {'slug': vipComment.user.slug})}}"><img src="/uploads/photos/userPhotos/{{vipComment.user.profilePicture}}" alt="{{vipComment.user}}-profile-picture"></a>
                        {% else %}
                            <a class="ppLink" href="{{ path('show_user', {'slug': vipComment.user.slug})}}"><img src="/uploads/photos/userPhotos/user-default.png" alt="user-default-profile-picture"></a>
                        {% endif %}

                        <div class="mainComment">
                            <a href="{{ path('show_user', {'slug': vipComment.user.slug})}}"><strong>{{vipComment.user}}</a> - </strong>
                            <span>{{vipComment.datePostENG}}</span><br>

                            <div id="vipCommentUserScoreHome">

                            {# > User score fetch #}
                            {% set userScore = null %}
                            {% for opinion in vipComment.user.opinions %}
                                {% if opinion.piece.id == vipComment.critic.piece.id %}
                                    {% set userScore = opinion.userScore %}
                                {% endif %}
                            {% endfor %}
                                
                                {% if userScore %}

                                    <h4>Score :</h4>

                                    {# > Star score system #}
                                    {% set note = userScore %}
                                    {# {% set fullStars = note|round(0, 'floor') %} #}
                                    {% set fullStars = note %}
                                    {# {% set partialStar = (note - fullStars)|round(0, 'ceil') %} #}
                                    {% set emptyStars = 5 - fullStars %}
                                    {# {% set emptyStars = 5 - fullStars - (partialStar ? 1 : 0) %} #}

                                    <div>
                                        {% for i in range(1, fullStars) %}
                                            <i class="fa-solid fa-star fullstars"></i>
                                        {% endfor %}

                                        {# {% if partialStar %}
                                            <i class="fa-solid fa-star-half-stroke halfstars"></i>
                                        {% endif %} #}

                                        {% if emptyStars %}
                                            {% for i in range(1, emptyStars) %}
                                                <i class="fa-solid fa-star emptystars"></i>
                                            {% endfor %}
                                        {% endif %}
                                    </div>

                                {% endif %}
                            </div>

                            <p>{{vipComment.text}}</p>
                        </div>
                    </div>
                </article>

            <h3>On : <a href="{{ path('show_critics', {'slug': vipComment.critic.piece.slug})}}#critic-{{vipComment.critic.id}}">{{vipComment.critic.piece}}</a></h3>
            <i>#{{vipComment.critic.piece.category}}</i>
            </div>
            {% endfor %}
        </div>
    </section>

    <a href="#homeLink" aria-label="Return Up Button"><i class="fa-regular fa-circle-up"></i></a>
</div>

{% endblock %}

templates/home/legal.html.twig
{% extends 'base.html.twig' %}

{% block title %}CritX > Legal Terms{% endblock %}

{% block body %}

<div class="footInfosContainer">
    <div class="footInfos" id="legalInfos">
        <h1>Legal Terms</h1>

        <p>The French government, in a good conduct 
        <a href="https://www.economie.gouv.fr/files/files/2023/Guide_bonne_conduite_influenceurs_createurs_contenus.pdf?v=1738331205" target="_blank">guide</a> 
        for influencers and content creators, dated June 2023, sets out the essential rights and duties of the profession.</p>
        
        <p>Article 11 of the text states :</p>
        <blockquote><em>"If you create content in an original form, your content is protected by copyright rules. As such, you have moral and economic rights over your content.
        Under moral rights, you can decide on the principle, timing and conditions of disclosure of your content, as well as its continued circulation. 
        You can also demand that every time your content is used, your name is mentioned and the integrity of your content is respected.
        In terms of economic rights, you may authorise or prohibit reproductions or representations of your content.
        Consequently, any use of your content will require your authorisation. A third party will therefore not be able to re-use your publications 
        and/or videos without first obtaining rights from you."</em></blockquote>

        <p>In accordance with this text, any sharing on the CritX website pages of a content created by an influencer 
        (and initially released on a third-party platform) is part of a partnership established with the said content creator, 
        whether it be a financial partnership or a simple exchange of visibility between CritX and the content creator.</p>
    </div>
<div>

{% endblock %}